application: myapplication
version: 1
runtime: python
api_version: 1

handlers:
- url: /wiki/(.+)
  script: MarkdownWiki/wiki.py

#- url: /wiki_reset
#  script: MarkdownWiki/wiki_reset.py	

- url: /(.[^/]*)/(.*\.(html|jpg|png|gif|ico|js|css))
  static_files: \1/static/\2
  upload: (.[^/]*)/static/(.*\.(html|jpg|png|gif|ico|js|css))
